"""empty message

Revision ID: 021285003a4b
Revises: 7cc016e174a4
Create Date: 2020-02-16 16:13:04.827022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '021285003a4b'
down_revision = '7cc016e174a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planned_task', sa.Column('signature', sa.String(length=100), nullable=False))
    op.add_column('task', sa.Column('signature', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'signature')
    op.drop_column('planned_task', 'signature')
    # ### end Alembic commands ###
