"""empty message

Revision ID: 129e59092437
Revises: 67043f3f96c8
Create Date: 2020-02-10 15:27:39.161247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '129e59092437'
down_revision = '67043f3f96c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit', sa.Column('icon_name', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habit', 'icon_name')
    # ### end Alembic commands ###
