"""empty message

Revision ID: 1736a71b62c8
Revises: 129e59092437
Create Date: 2020-02-10 23:51:06.872446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1736a71b62c8'
down_revision = '129e59092437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('habit_ibfk_1', 'habit', type_='foreignkey')
    op.create_foreign_key(None, 'habit', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('habit_counter_ibfk_1', 'habit_counter', type_='foreignkey')
    op.create_foreign_key(None, 'habit_counter', 'habit', ['habit_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('planned_task_ibfk_1', 'planned_task', type_='foreignkey')
    op.create_foreign_key(None, 'planned_task', 'task', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('task_ibfk_1', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('user', sa.Column('ranking', sa.Enum('STARTER', 'ENROLLED', 'EXPERIENCED', 'VETERAN', name='userranking'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'ranking')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_ibfk_1', 'task', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'planned_task', type_='foreignkey')
    op.create_foreign_key('planned_task_ibfk_1', 'planned_task', 'task', ['task_id'], ['id'])
    op.drop_constraint(None, 'habit_counter', type_='foreignkey')
    op.create_foreign_key('habit_counter_ibfk_1', 'habit_counter', 'habit', ['habit_id'], ['id'])
    op.drop_constraint(None, 'habit', type_='foreignkey')
    op.create_foreign_key('habit_ibfk_1', 'habit', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
