"""empty message

Revision ID: 2eb444558f59
Revises: 4e02ddf5ad77
Create Date: 2020-02-12 17:04:33.924392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eb444558f59'
down_revision = '4e02ddf5ad77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planned_task', sa.Column('is_any', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planned_task', 'is_any')
    # ### end Alembic commands ###
