"""empty message

Revision ID: 37149e5c628d
Revises: 86bf0c93eedf
Create Date: 2020-02-20 17:02:23.559860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37149e5c628d'
down_revision = '86bf0c93eedf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit', sa.Column('signature', sa.String(length=100), nullable=False))
    op.add_column('habit_counter', sa.Column('signature', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habit_counter', 'signature')
    op.drop_column('habit', 'signature')
    # ### end Alembic commands ###
