"""empty message

Revision ID: 86bf0c93eedf
Revises: e55282f71229
Create Date: 2020-02-20 05:25:47.608456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '86bf0c93eedf'
down_revision = 'e55282f71229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_kpi', sa.Column('best_average', sa.Float(), nullable=False))
    op.drop_column('task_kpi', 'current_streak')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_kpi', sa.Column('current_streak', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('task_kpi', 'best_average')
    # ### end Alembic commands ###
