"""empty message

Revision ID: cd6844889234
Revises: 36b694942a74
Create Date: 2020-02-27 22:53:21.062865

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd6844889234'
down_revision = '36b694942a74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habit_introspective',
    sa.Column('previous_activity', sa.String(length=100), nullable=True),
    sa.Column('next_activity', sa.String(length=100), nullable=True),
    sa.Column('as_felt_before', sa.Enum('SADDER', 'SAD', 'INDIFFERENT', 'HAPPY', 'HAPPIER', name='feeling'), nullable=False),
    sa.Column('as_felt_afterwards', sa.Enum('SADDER', 'SAD', 'INDIFFERENT', 'HAPPY', 'HAPPIER', name='feeling'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habit_counter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['habit_counter_id'], ['habit_counter.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('task_introspective',
    sa.Column('previous_activity', sa.String(length=100), nullable=True),
    sa.Column('next_activity', sa.String(length=100), nullable=True),
    sa.Column('as_felt_before', sa.Enum('SADDER', 'SAD', 'INDIFFERENT', 'HAPPY', 'HAPPIER', name='feeling'), nullable=False),
    sa.Column('as_felt_afterwards', sa.Enum('SADDER', 'SAD', 'INDIFFERENT', 'HAPPY', 'HAPPIER', name='feeling'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planned_task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planned_task_id'], ['planned_task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.drop_column('habit_counter', 'as_felt_before')
    op.drop_column('habit_counter', 'next_activity')
    op.drop_column('habit_counter', 'previous_activity')
    op.drop_column('habit_counter', 'as_felt_afterwards')
    op.drop_column('planned_task', 'as_felt_before')
    op.drop_column('planned_task', 'next_activity')
    op.drop_column('planned_task', 'previous_activity')
    op.drop_column('planned_task', 'as_felt_afterwards')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planned_task', sa.Column('as_felt_afterwards', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('planned_task', sa.Column('previous_activity', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('planned_task', sa.Column('next_activity', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('planned_task', sa.Column('as_felt_before', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('habit_counter', sa.Column('as_felt_afterwards', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('habit_counter', sa.Column('previous_activity', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('habit_counter', sa.Column('next_activity', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('habit_counter', sa.Column('as_felt_before', mysql.VARCHAR(length=120), nullable=True))
    op.drop_table('task_introspective')
    op.drop_table('habit_introspective')
    # ### end Alembic commands ###
