"""empty message

Revision ID: dd23276ff7cc
Revises: 45d1f39f8792
Create Date: 2020-02-07 21:42:18.651809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd23276ff7cc'
down_revision = '45d1f39f8792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_habit_for_user', 'habit', ['user_id', 'name'])
    op.create_unique_constraint('unique_date_for_habit_counter', 'habit_counter', ['date_for_count', 'habit_id'])
    op.create_unique_constraint('unique_datetime_for_task', 'planned_task', ['planned_datetime', 'task_id'])
    op.create_unique_constraint('unique_task_for_user', 'task', ['user_id', 'name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_task_for_user', 'task', type_='unique')
    op.drop_constraint('unique_datetime_for_task', 'planned_task', type_='unique')
    op.drop_constraint('unique_date_for_habit_counter', 'habit_counter', type_='unique')
    op.drop_constraint('unique_habit_for_user', 'habit', type_='unique')
    # ### end Alembic commands ###
