"""empty message

Revision ID: de9c32b86eb6
Revises: dd23276ff7cc
Create Date: 2020-02-08 05:28:10.015167

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de9c32b86eb6'
down_revision = 'dd23276ff7cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habit', sa.Column('to_be_enforced', sa.Boolean(), nullable=False))
    op.drop_column('habit_counter', 'to_be_enforced')
    op.alter_column('planned_task', 'marked_done_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('planned_task', 'registered_duration',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('planned_task', 'registered_duration',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('planned_task', 'marked_done_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.add_column('habit_counter', sa.Column('to_be_enforced', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('habit', 'to_be_enforced')
    # ### end Alembic commands ###
