"""empty message

Revision ID: fe504bc6bc1a
Revises: 37149e5c628d
Create Date: 2020-02-21 16:59:52.176322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe504bc6bc1a'
down_revision = '37149e5c628d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('member_since', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'member_since')
    # ### end Alembic commands ###
